export const deliveryStates = [
  { value: "andhra pradesh", label: "Andhra Pradesh" },
  { value: "arunachal pradesh", label: "Arunachal Pradesh" },
  { value: "assam", label: "Assam" },
  { value: "bihar", label: "Bihar" },
  { value: "chattisgarh", label: "Chattisgarh" },
  { value: "goa", label: "Goa" },
  { value: "gujarat", label: "Gujarat" },
  { value: "harayana", label: "Harayana" },
  { value: "himachal pradesh", label: "Himachal Pradesh" },
  { value: "jharkhand", label: "Jharkhand" },
  { value: "karnataka", label: "Karnataka" },
  { value: "kerala", label: "Kerala" },
  { value: "madhya pradesh", label: "Madhya Pradesh" },
  { value: "maharastra", label: "Maharastra" },
  { value: "manipur", label: "Manipur" },
  { value: "meghalaya", label: "Meghalaya" },
  { value: "mizoram", label: "Mizoram" },
  { value: "nagaland", label: "Nagaland" },
  { value: "odisha", label: "Odisha" },
  { value: "punjab", label: "Punjab" },
  { value: "rajasthan", label: "Rajasthan" },
  { value: "sikkim", label: "Sikkim" },
  { value: "tamilnadu", label: "Tamilnadu" },
  { value: "telangana", label: "Telangana" },
  { value: "tripura", label: "Tripura" },
  { value: "uttar pradesh", label: "Uttar Pradesh" },
  { value: "uttarkhand", label: "Uttarakhand" },
  { value: "west bengal", label: "West Bengal" },
];
